### ISSUE TITLE
Package names used only in IDEs: fails from command prompt

### ISSUE THREAD

**Issue by tmcclintock** [bhudnell1240/Spells#2]
When I tried to run controller.class from within the src/backend/ folder I was met with the following errors:

Exception in thread "main" java.lang.NoClassDefFoundError: controller (wrong name: backend/controller)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

After a google search of the error I found [this stackoverflow thread](http://stackoverflow.com/questions/6334148/exception-in-thread-main-java-lang-noclassdeffounderror). Apparently when a java program is developed in an IDE it puts lines like
```
package backend;
```
at the top, but this throws an error when running from the command line. Commenting out the "package blahblah;" lines fixes this.

**Comment by bhudnell** [comment]
Thanks for the heads up. Ill remove that line for future updates.
